name: Sync to GCS

on:
  push:
    branches: [ main ]  # You can change this to any branch

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Upload to GCS
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: frontier.js
          destination: gs://nextera-gb/
          parent: false  # Set to true if you want to preserve directory structure
